# Usar una imagen base ligera de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios al contenedor
COPY requirements.txt ./requirements.txt
COPY app ./app
COPY components ./components
COPY assets ./assets

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto que usará la aplicación Dash
EXPOSE 8050

# Comando para ejecutar el Dashboard
CMD ["python", "app/main.py"]
