# Usar una imagen base ligera de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiar los archivos necesarios al contenedor
COPY requirements.txt ./requirements.txt
COPY app ./app
COPY modelo_kmeans.pkl ./modelo_kmeans.pkl
COPY modelo_random_forest_cluster_0.pkl ./modelo_random_forest_cluster_0.pkl
COPY modelo_random_forest_cluster_1.pkl ./modelo_random_forest_cluster_1.pkl

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Exponer el puerto que usará la API
EXPOSE 8000

# Comando para ejecutar la API
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
