FROM python:3.10

# Crear usuario para ejecutar la app
RUN adduser --disabled-password --gecos '' api-user

# Definir el directorio de trabajo
WORKDIR /app

# Copiar el código de la aplicación
ADD ./ /app/

# Instalar dependencias
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt

# Cambiar permisos de la carpeta
RUN chmod +x /app
RUN chown -R api-user:api-user ./ 

# Cambiar a usuario creado para ejecutar la aplicación
USER api-user

# Exponer el puerto de la API
EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
